query homePageData(
  $relativePath: String!
  $before: String
  $after: String
  $first: Float
  $last: Float
  $sort: String
  $filter: ProductFilter
) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
  productConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    edges {
      node {
        ... on Document {
          _sys {
            filename
          }
          id
          ...HomePageProductParts
        }
      }
    }
  }
}

query footerData(
  $before: String
  $after: String
  $first: Float
  $last: Float
  $sort: String
  $filter: GlobalFilter
) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    edges {
      node {
        ...FooterDetails
      }
    }
  }
}
