fragment GlobalCollectionParts on GlobalCollection {
  header {
    __typename
    phoneNumber
    socialLinks {
      __typename
      label
      url
    }
    logo
    navigation {
      __typename
      label
      url
      subNavItem {
        __typename
        label
        url
      }
    }
  }
  footer {
    __typename
    label
  }
}

fragment HomePageCollectionParts on HomePageCollection {
  metadata {
    __typename
    title
    description
  }
  heroImage
  cta
  body
  quotes {
    __typename
    quote
    name
  }
}

fragment FlavorPageCollectionParts on FlavorPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  body
  heroImage
  flavorGroups {
    __typename
    label
    flavors
  }
}

fragment ProductPageCollectionParts on ProductPageCollection {
  metadata {
    __typename
    title
    description
  }
  hidden
  title
  body
  images {
    __typename
    image
  }
}

fragment PoliciesAndPricingPageCollectionParts on PoliciesAndPricingPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  heroImage
  body
}

fragment AboutUsPageCollectionParts on AboutUsPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  newOwnershipBody
  ownerPhotos {
    __typename
    image
  }
  aboutTheFounderBody
  founderPhotos {
    __typename
    image
  }
}

fragment AboutThisWebsitePageCollectionParts on AboutThisWebsitePageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  body
}

fragment ContactUsPageCollectionParts on ContactUsPageCollection {
  metadata {
    __typename
    title
    description
  }
  contactDetails
}
