//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  GlobalCollection: GlobalCollection;
  GlobalCollectionConnection: GlobalCollectionConnection;
  HomePageCollection: HomePageCollection;
  HomePageCollectionConnection: HomePageCollectionConnection;
  FlavorPageCollection: FlavorPageCollection;
  FlavorPageCollectionConnection: FlavorPageCollectionConnection;
  ProductPageCollection: ProductPageCollection;
  ProductPageCollectionConnection: ProductPageCollectionConnection;
  PoliciesAndPricingPageCollection: PoliciesAndPricingPageCollection;
  PoliciesAndPricingPageCollectionConnection: PoliciesAndPricingPageCollectionConnection;
  AboutUsPageCollection: AboutUsPageCollection;
  AboutUsPageCollectionConnection: AboutUsPageCollectionConnection;
  AboutThisWebsitePageCollection: AboutThisWebsitePageCollection;
  AboutThisWebsitePageCollectionConnection: AboutThisWebsitePageCollectionConnection;
  ContactUsPageCollection: ContactUsPageCollection;
  ContactUsPageCollectionConnection: ContactUsPageCollectionConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalCollectionFilter>;
};


export type QueryHomePageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageCollectionFilter>;
};


export type QueryFlavorPageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFlavorPageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FlavorPageCollectionFilter>;
};


export type QueryProductPageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProductPageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductPageCollectionFilter>;
};


export type QueryPoliciesAndPricingPageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPoliciesAndPricingPageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PoliciesAndPricingPageCollectionFilter>;
};


export type QueryAboutUsPageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutUsPageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutUsPageCollectionFilter>;
};


export type QueryAboutThisWebsitePageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutThisWebsitePageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutThisWebsitePageCollectionFilter>;
};


export type QueryContactUsPageCollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactUsPageCollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactUsPageCollectionFilter>;
};

export type DocumentFilter = {
  GlobalCollection?: InputMaybe<GlobalCollectionFilter>;
  HomePageCollection?: InputMaybe<HomePageCollectionFilter>;
  FlavorPageCollection?: InputMaybe<FlavorPageCollectionFilter>;
  ProductPageCollection?: InputMaybe<ProductPageCollectionFilter>;
  PoliciesAndPricingPageCollection?: InputMaybe<PoliciesAndPricingPageCollectionFilter>;
  AboutUsPageCollection?: InputMaybe<AboutUsPageCollectionFilter>;
  AboutThisWebsitePageCollection?: InputMaybe<AboutThisWebsitePageCollectionFilter>;
  ContactUsPageCollection?: InputMaybe<ContactUsPageCollectionFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = GlobalCollection | HomePageCollection | FlavorPageCollection | ProductPageCollection | PoliciesAndPricingPageCollection | AboutUsPageCollection | AboutThisWebsitePageCollection | ContactUsPageCollection | Folder;

export type GlobalCollectionHeaderSocialLinks = {
  __typename?: 'GlobalCollectionHeaderSocialLinks';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type GlobalCollectionHeaderNavigationSubNavItem = {
  __typename?: 'GlobalCollectionHeaderNavigationSubNavItem';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type GlobalCollectionHeaderNavigation = {
  __typename?: 'GlobalCollectionHeaderNavigation';
  label: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
  subNavItem?: Maybe<Array<Maybe<GlobalCollectionHeaderNavigationSubNavItem>>>;
};

export type GlobalCollectionHeader = {
  __typename?: 'GlobalCollectionHeader';
  phoneNumber: Scalars['String']['output'];
  socialLinks?: Maybe<Array<Maybe<GlobalCollectionHeaderSocialLinks>>>;
  logo: Scalars['String']['output'];
  navigation?: Maybe<Array<Maybe<GlobalCollectionHeaderNavigation>>>;
};

export type GlobalCollectionFooter = {
  __typename?: 'GlobalCollectionFooter';
  label: Scalars['String']['output'];
};

export type GlobalCollection = Node & Document & {
  __typename?: 'GlobalCollection';
  header?: Maybe<GlobalCollectionHeader>;
  footer?: Maybe<GlobalCollectionFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GlobalCollectionHeaderSocialLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GlobalCollectionHeaderNavigationSubNavItemFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type GlobalCollectionHeaderNavigationFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  subNavItem?: InputMaybe<GlobalCollectionHeaderNavigationSubNavItemFilter>;
};

export type GlobalCollectionHeaderFilter = {
  phoneNumber?: InputMaybe<StringFilter>;
  socialLinks?: InputMaybe<GlobalCollectionHeaderSocialLinksFilter>;
  logo?: InputMaybe<ImageFilter>;
  navigation?: InputMaybe<GlobalCollectionHeaderNavigationFilter>;
};

export type GlobalCollectionFooterFilter = {
  label?: InputMaybe<StringFilter>;
};

export type GlobalCollectionFilter = {
  header?: InputMaybe<GlobalCollectionHeaderFilter>;
  footer?: InputMaybe<GlobalCollectionFooterFilter>;
};

export type GlobalCollectionConnectionEdges = {
  __typename?: 'GlobalCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<GlobalCollection>;
};

export type GlobalCollectionConnection = Connection & {
  __typename?: 'GlobalCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalCollectionConnectionEdges>>>;
};

export type HomePageCollectionMetadata = {
  __typename?: 'HomePageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomePageCollectionQuotes = {
  __typename?: 'HomePageCollectionQuotes';
  quote: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type HomePageCollection = Node & Document & {
  __typename?: 'HomePageCollection';
  metadata?: Maybe<HomePageCollectionMetadata>;
  heroImage?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  quotes?: Maybe<Array<Maybe<HomePageCollectionQuotes>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomePageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomePageCollectionQuotesFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type HomePageCollectionFilter = {
  metadata?: InputMaybe<HomePageCollectionMetadataFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  cta?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  quotes?: InputMaybe<HomePageCollectionQuotesFilter>;
};

export type HomePageCollectionConnectionEdges = {
  __typename?: 'HomePageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePageCollection>;
};

export type HomePageCollectionConnection = Connection & {
  __typename?: 'HomePageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageCollectionConnectionEdges>>>;
};

export type FlavorPageCollectionMetadata = {
  __typename?: 'FlavorPageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type FlavorPageCollectionFlavorGroups = {
  __typename?: 'FlavorPageCollectionFlavorGroups';
  label: Scalars['String']['output'];
  flavors: Array<Scalars['String']['output']>;
};

export type FlavorPageCollection = Node & Document & {
  __typename?: 'FlavorPageCollection';
  metadata?: Maybe<FlavorPageCollectionMetadata>;
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  heroImage: Scalars['String']['output'];
  flavorGroups?: Maybe<Array<Maybe<FlavorPageCollectionFlavorGroups>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FlavorPageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type FlavorPageCollectionFlavorGroupsFilter = {
  label?: InputMaybe<StringFilter>;
  flavors?: InputMaybe<StringFilter>;
};

export type FlavorPageCollectionFilter = {
  metadata?: InputMaybe<FlavorPageCollectionMetadataFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  flavorGroups?: InputMaybe<FlavorPageCollectionFlavorGroupsFilter>;
};

export type FlavorPageCollectionConnectionEdges = {
  __typename?: 'FlavorPageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FlavorPageCollection>;
};

export type FlavorPageCollectionConnection = Connection & {
  __typename?: 'FlavorPageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FlavorPageCollectionConnectionEdges>>>;
};

export type ProductPageCollectionMetadata = {
  __typename?: 'ProductPageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ProductPageCollectionImages = {
  __typename?: 'ProductPageCollectionImages';
  image: Scalars['String']['output'];
};

export type ProductPageCollection = Node & Document & {
  __typename?: 'ProductPageCollection';
  metadata?: Maybe<ProductPageCollectionMetadata>;
  hidden?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  images?: Maybe<Array<Maybe<ProductPageCollectionImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProductPageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProductPageCollectionImagesFilter = {
  image?: InputMaybe<ImageFilter>;
};

export type ProductPageCollectionFilter = {
  metadata?: InputMaybe<ProductPageCollectionMetadataFilter>;
  hidden?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  images?: InputMaybe<ProductPageCollectionImagesFilter>;
};

export type ProductPageCollectionConnectionEdges = {
  __typename?: 'ProductPageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ProductPageCollection>;
};

export type ProductPageCollectionConnection = Connection & {
  __typename?: 'ProductPageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProductPageCollectionConnectionEdges>>>;
};

export type PoliciesAndPricingPageCollectionMetadata = {
  __typename?: 'PoliciesAndPricingPageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PoliciesAndPricingPageCollection = Node & Document & {
  __typename?: 'PoliciesAndPricingPageCollection';
  metadata?: Maybe<PoliciesAndPricingPageCollectionMetadata>;
  title: Scalars['String']['output'];
  heroImage: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PoliciesAndPricingPageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PoliciesAndPricingPageCollectionFilter = {
  metadata?: InputMaybe<PoliciesAndPricingPageCollectionMetadataFilter>;
  title?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PoliciesAndPricingPageCollectionConnectionEdges = {
  __typename?: 'PoliciesAndPricingPageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PoliciesAndPricingPageCollection>;
};

export type PoliciesAndPricingPageCollectionConnection = Connection & {
  __typename?: 'PoliciesAndPricingPageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PoliciesAndPricingPageCollectionConnectionEdges>>>;
};

export type AboutUsPageCollectionMetadata = {
  __typename?: 'AboutUsPageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutUsPageCollectionOwnerPhotos = {
  __typename?: 'AboutUsPageCollectionOwnerPhotos';
  image: Scalars['String']['output'];
};

export type AboutUsPageCollectionFounderPhotos = {
  __typename?: 'AboutUsPageCollectionFounderPhotos';
  image: Scalars['String']['output'];
};

export type AboutUsPageCollection = Node & Document & {
  __typename?: 'AboutUsPageCollection';
  metadata?: Maybe<AboutUsPageCollectionMetadata>;
  title: Scalars['String']['output'];
  newOwnershipBody?: Maybe<Scalars['JSON']['output']>;
  ownerPhotos?: Maybe<Array<Maybe<AboutUsPageCollectionOwnerPhotos>>>;
  aboutTheFounderBody?: Maybe<Scalars['JSON']['output']>;
  founderPhotos?: Maybe<Array<Maybe<AboutUsPageCollectionFounderPhotos>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutUsPageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutUsPageCollectionOwnerPhotosFilter = {
  image?: InputMaybe<ImageFilter>;
};

export type AboutUsPageCollectionFounderPhotosFilter = {
  image?: InputMaybe<ImageFilter>;
};

export type AboutUsPageCollectionFilter = {
  metadata?: InputMaybe<AboutUsPageCollectionMetadataFilter>;
  title?: InputMaybe<StringFilter>;
  newOwnershipBody?: InputMaybe<RichTextFilter>;
  ownerPhotos?: InputMaybe<AboutUsPageCollectionOwnerPhotosFilter>;
  aboutTheFounderBody?: InputMaybe<RichTextFilter>;
  founderPhotos?: InputMaybe<AboutUsPageCollectionFounderPhotosFilter>;
};

export type AboutUsPageCollectionConnectionEdges = {
  __typename?: 'AboutUsPageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<AboutUsPageCollection>;
};

export type AboutUsPageCollectionConnection = Connection & {
  __typename?: 'AboutUsPageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutUsPageCollectionConnectionEdges>>>;
};

export type AboutThisWebsitePageCollectionMetadata = {
  __typename?: 'AboutThisWebsitePageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutThisWebsitePageCollection = Node & Document & {
  __typename?: 'AboutThisWebsitePageCollection';
  metadata?: Maybe<AboutThisWebsitePageCollectionMetadata>;
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutThisWebsitePageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutThisWebsitePageCollectionFilter = {
  metadata?: InputMaybe<AboutThisWebsitePageCollectionMetadataFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AboutThisWebsitePageCollectionConnectionEdges = {
  __typename?: 'AboutThisWebsitePageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<AboutThisWebsitePageCollection>;
};

export type AboutThisWebsitePageCollectionConnection = Connection & {
  __typename?: 'AboutThisWebsitePageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutThisWebsitePageCollectionConnectionEdges>>>;
};

export type ContactUsPageCollectionMetadata = {
  __typename?: 'ContactUsPageCollectionMetadata';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ContactUsPageCollection = Node & Document & {
  __typename?: 'ContactUsPageCollection';
  metadata?: Maybe<ContactUsPageCollectionMetadata>;
  contactDetails?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactUsPageCollectionMetadataFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ContactUsPageCollectionFilter = {
  metadata?: InputMaybe<ContactUsPageCollectionMetadataFilter>;
  contactDetails?: InputMaybe<RichTextFilter>;
};

export type ContactUsPageCollectionConnectionEdges = {
  __typename?: 'ContactUsPageCollectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactUsPageCollection>;
};

export type ContactUsPageCollectionConnection = Connection & {
  __typename?: 'ContactUsPageCollectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactUsPageCollectionConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateGlobalCollection: GlobalCollection;
  createGlobalCollection: GlobalCollection;
  updateHomePageCollection: HomePageCollection;
  createHomePageCollection: HomePageCollection;
  updateFlavorPageCollection: FlavorPageCollection;
  createFlavorPageCollection: FlavorPageCollection;
  updateProductPageCollection: ProductPageCollection;
  createProductPageCollection: ProductPageCollection;
  updatePoliciesAndPricingPageCollection: PoliciesAndPricingPageCollection;
  createPoliciesAndPricingPageCollection: PoliciesAndPricingPageCollection;
  updateAboutUsPageCollection: AboutUsPageCollection;
  createAboutUsPageCollection: AboutUsPageCollection;
  updateAboutThisWebsitePageCollection: AboutThisWebsitePageCollection;
  createAboutThisWebsitePageCollection: AboutThisWebsitePageCollection;
  updateContactUsPageCollection: ContactUsPageCollection;
  createContactUsPageCollection: ContactUsPageCollection;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdateGlobalCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalCollectionMutation;
};


export type MutationCreateGlobalCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalCollectionMutation;
};


export type MutationUpdateHomePageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageCollectionMutation;
};


export type MutationCreateHomePageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageCollectionMutation;
};


export type MutationUpdateFlavorPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: FlavorPageCollectionMutation;
};


export type MutationCreateFlavorPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: FlavorPageCollectionMutation;
};


export type MutationUpdateProductPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductPageCollectionMutation;
};


export type MutationCreateProductPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductPageCollectionMutation;
};


export type MutationUpdatePoliciesAndPricingPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: PoliciesAndPricingPageCollectionMutation;
};


export type MutationCreatePoliciesAndPricingPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: PoliciesAndPricingPageCollectionMutation;
};


export type MutationUpdateAboutUsPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutUsPageCollectionMutation;
};


export type MutationCreateAboutUsPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutUsPageCollectionMutation;
};


export type MutationUpdateAboutThisWebsitePageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutThisWebsitePageCollectionMutation;
};


export type MutationCreateAboutThisWebsitePageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutThisWebsitePageCollectionMutation;
};


export type MutationUpdateContactUsPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactUsPageCollectionMutation;
};


export type MutationCreateContactUsPageCollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactUsPageCollectionMutation;
};

export type DocumentUpdateMutation = {
  GlobalCollection?: InputMaybe<GlobalCollectionMutation>;
  HomePageCollection?: InputMaybe<HomePageCollectionMutation>;
  FlavorPageCollection?: InputMaybe<FlavorPageCollectionMutation>;
  ProductPageCollection?: InputMaybe<ProductPageCollectionMutation>;
  PoliciesAndPricingPageCollection?: InputMaybe<PoliciesAndPricingPageCollectionMutation>;
  AboutUsPageCollection?: InputMaybe<AboutUsPageCollectionMutation>;
  AboutThisWebsitePageCollection?: InputMaybe<AboutThisWebsitePageCollectionMutation>;
  ContactUsPageCollection?: InputMaybe<ContactUsPageCollectionMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  GlobalCollection?: InputMaybe<GlobalCollectionMutation>;
  HomePageCollection?: InputMaybe<HomePageCollectionMutation>;
  FlavorPageCollection?: InputMaybe<FlavorPageCollectionMutation>;
  ProductPageCollection?: InputMaybe<ProductPageCollectionMutation>;
  PoliciesAndPricingPageCollection?: InputMaybe<PoliciesAndPricingPageCollectionMutation>;
  AboutUsPageCollection?: InputMaybe<AboutUsPageCollectionMutation>;
  AboutThisWebsitePageCollection?: InputMaybe<AboutThisWebsitePageCollectionMutation>;
  ContactUsPageCollection?: InputMaybe<ContactUsPageCollectionMutation>;
};

export type GlobalCollectionHeaderSocialLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalCollectionHeaderNavigationSubNavItemMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalCollectionHeaderNavigationMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  subNavItem?: InputMaybe<Array<InputMaybe<GlobalCollectionHeaderNavigationSubNavItemMutation>>>;
};

export type GlobalCollectionHeaderMutation = {
  phoneNumber?: InputMaybe<Scalars['String']['input']>;
  socialLinks?: InputMaybe<Array<InputMaybe<GlobalCollectionHeaderSocialLinksMutation>>>;
  logo?: InputMaybe<Scalars['String']['input']>;
  navigation?: InputMaybe<Array<InputMaybe<GlobalCollectionHeaderNavigationMutation>>>;
};

export type GlobalCollectionFooterMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalCollectionMutation = {
  header?: InputMaybe<GlobalCollectionHeaderMutation>;
  footer?: InputMaybe<GlobalCollectionFooterMutation>;
};

export type HomePageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageCollectionQuotesMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageCollectionMutation = {
  metadata?: InputMaybe<HomePageCollectionMetadataMutation>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  quotes?: InputMaybe<Array<InputMaybe<HomePageCollectionQuotesMutation>>>;
};

export type FlavorPageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type FlavorPageCollectionFlavorGroupsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  flavors?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FlavorPageCollectionMutation = {
  metadata?: InputMaybe<FlavorPageCollectionMetadataMutation>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  flavorGroups?: InputMaybe<Array<InputMaybe<FlavorPageCollectionFlavorGroupsMutation>>>;
};

export type ProductPageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ProductPageCollectionImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ProductPageCollectionMutation = {
  metadata?: InputMaybe<ProductPageCollectionMetadataMutation>;
  hidden?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  images?: InputMaybe<Array<InputMaybe<ProductPageCollectionImagesMutation>>>;
};

export type PoliciesAndPricingPageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PoliciesAndPricingPageCollectionMutation = {
  metadata?: InputMaybe<PoliciesAndPricingPageCollectionMetadataMutation>;
  title?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AboutUsPageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutUsPageCollectionOwnerPhotosMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
};

export type AboutUsPageCollectionFounderPhotosMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
};

export type AboutUsPageCollectionMutation = {
  metadata?: InputMaybe<AboutUsPageCollectionMetadataMutation>;
  title?: InputMaybe<Scalars['String']['input']>;
  newOwnershipBody?: InputMaybe<Scalars['JSON']['input']>;
  ownerPhotos?: InputMaybe<Array<InputMaybe<AboutUsPageCollectionOwnerPhotosMutation>>>;
  aboutTheFounderBody?: InputMaybe<Scalars['JSON']['input']>;
  founderPhotos?: InputMaybe<Array<InputMaybe<AboutUsPageCollectionFounderPhotosMutation>>>;
};

export type AboutThisWebsitePageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutThisWebsitePageCollectionMutation = {
  metadata?: InputMaybe<AboutThisWebsitePageCollectionMetadataMutation>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ContactUsPageCollectionMetadataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ContactUsPageCollectionMutation = {
  metadata?: InputMaybe<ContactUsPageCollectionMetadataMutation>;
  contactDetails?: InputMaybe<Scalars['JSON']['input']>;
};

export type GlobalCollectionPartsFragment = { __typename?: 'GlobalCollection', header?: { __typename: 'GlobalCollectionHeader', phoneNumber: string, logo: string, socialLinks?: Array<{ __typename: 'GlobalCollectionHeaderSocialLinks', label: string, url: string } | null> | null, navigation?: Array<{ __typename: 'GlobalCollectionHeaderNavigation', label: string, url?: string | null, subNavItem?: Array<{ __typename: 'GlobalCollectionHeaderNavigationSubNavItem', label: string, url: string } | null> | null } | null> | null } | null, footer?: { __typename: 'GlobalCollectionFooter', label: string } | null };

export type HomePageCollectionPartsFragment = { __typename?: 'HomePageCollection', heroImage?: string | null, cta?: string | null, body?: any | null, metadata?: { __typename: 'HomePageCollectionMetadata', title?: string | null, description?: string | null } | null, quotes?: Array<{ __typename: 'HomePageCollectionQuotes', quote: string, name: string } | null> | null };

export type FlavorPageCollectionPartsFragment = { __typename?: 'FlavorPageCollection', title: string, body?: any | null, heroImage: string, metadata?: { __typename: 'FlavorPageCollectionMetadata', title?: string | null, description?: string | null } | null, flavorGroups?: Array<{ __typename: 'FlavorPageCollectionFlavorGroups', label: string, flavors: Array<string> } | null> | null };

export type ProductPageCollectionPartsFragment = { __typename?: 'ProductPageCollection', hidden?: boolean | null, title: string, body?: any | null, metadata?: { __typename: 'ProductPageCollectionMetadata', title?: string | null, description?: string | null } | null, images?: Array<{ __typename: 'ProductPageCollectionImages', image: string } | null> | null };

export type PoliciesAndPricingPageCollectionPartsFragment = { __typename?: 'PoliciesAndPricingPageCollection', title: string, heroImage: string, body?: any | null, metadata?: { __typename: 'PoliciesAndPricingPageCollectionMetadata', title?: string | null, description?: string | null } | null };

export type AboutUsPageCollectionPartsFragment = { __typename?: 'AboutUsPageCollection', title: string, newOwnershipBody?: any | null, aboutTheFounderBody?: any | null, metadata?: { __typename: 'AboutUsPageCollectionMetadata', title?: string | null, description?: string | null } | null, ownerPhotos?: Array<{ __typename: 'AboutUsPageCollectionOwnerPhotos', image: string } | null> | null, founderPhotos?: Array<{ __typename: 'AboutUsPageCollectionFounderPhotos', image: string } | null> | null };

export type AboutThisWebsitePageCollectionPartsFragment = { __typename?: 'AboutThisWebsitePageCollection', title: string, body?: any | null, metadata?: { __typename: 'AboutThisWebsitePageCollectionMetadata', title?: string | null, description?: string | null } | null };

export type ContactUsPageCollectionPartsFragment = { __typename?: 'ContactUsPageCollection', contactDetails?: any | null, metadata?: { __typename: 'ContactUsPageCollectionMetadata', title?: string | null, description?: string | null } | null };

export type GlobalCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalCollectionQuery = { __typename?: 'Query', GlobalCollection: { __typename?: 'GlobalCollection', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, header?: { __typename: 'GlobalCollectionHeader', phoneNumber: string, logo: string, socialLinks?: Array<{ __typename: 'GlobalCollectionHeaderSocialLinks', label: string, url: string } | null> | null, navigation?: Array<{ __typename: 'GlobalCollectionHeaderNavigation', label: string, url?: string | null, subNavItem?: Array<{ __typename: 'GlobalCollectionHeaderNavigationSubNavItem', label: string, url: string } | null> | null } | null> | null } | null, footer?: { __typename: 'GlobalCollectionFooter', label: string } | null } };

export type GlobalCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalCollectionFilter>;
}>;


export type GlobalCollectionConnectionQuery = { __typename?: 'Query', GlobalCollectionConnection: { __typename?: 'GlobalCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalCollectionConnectionEdges', cursor: string, node?: { __typename?: 'GlobalCollection', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, header?: { __typename: 'GlobalCollectionHeader', phoneNumber: string, logo: string, socialLinks?: Array<{ __typename: 'GlobalCollectionHeaderSocialLinks', label: string, url: string } | null> | null, navigation?: Array<{ __typename: 'GlobalCollectionHeaderNavigation', label: string, url?: string | null, subNavItem?: Array<{ __typename: 'GlobalCollectionHeaderNavigationSubNavItem', label: string, url: string } | null> | null } | null> | null } | null, footer?: { __typename: 'GlobalCollectionFooter', label: string } | null } | null } | null> | null } };

export type HomePageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageCollectionQuery = { __typename?: 'Query', HomePageCollection: { __typename?: 'HomePageCollection', id: string, heroImage?: string | null, cta?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'HomePageCollectionMetadata', title?: string | null, description?: string | null } | null, quotes?: Array<{ __typename: 'HomePageCollectionQuotes', quote: string, name: string } | null> | null } };

export type HomePageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageCollectionFilter>;
}>;


export type HomePageCollectionConnectionQuery = { __typename?: 'Query', HomePageCollectionConnection: { __typename?: 'HomePageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'HomePageCollection', id: string, heroImage?: string | null, cta?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'HomePageCollectionMetadata', title?: string | null, description?: string | null } | null, quotes?: Array<{ __typename: 'HomePageCollectionQuotes', quote: string, name: string } | null> | null } | null } | null> | null } };

export type FlavorPageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FlavorPageCollectionQuery = { __typename?: 'Query', FlavorPageCollection: { __typename?: 'FlavorPageCollection', id: string, title: string, body?: any | null, heroImage: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'FlavorPageCollectionMetadata', title?: string | null, description?: string | null } | null, flavorGroups?: Array<{ __typename: 'FlavorPageCollectionFlavorGroups', label: string, flavors: Array<string> } | null> | null } };

export type FlavorPageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FlavorPageCollectionFilter>;
}>;


export type FlavorPageCollectionConnectionQuery = { __typename?: 'Query', FlavorPageCollectionConnection: { __typename?: 'FlavorPageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FlavorPageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'FlavorPageCollection', id: string, title: string, body?: any | null, heroImage: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'FlavorPageCollectionMetadata', title?: string | null, description?: string | null } | null, flavorGroups?: Array<{ __typename: 'FlavorPageCollectionFlavorGroups', label: string, flavors: Array<string> } | null> | null } | null } | null> | null } };

export type ProductPageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProductPageCollectionQuery = { __typename?: 'Query', ProductPageCollection: { __typename?: 'ProductPageCollection', id: string, hidden?: boolean | null, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'ProductPageCollectionMetadata', title?: string | null, description?: string | null } | null, images?: Array<{ __typename: 'ProductPageCollectionImages', image: string } | null> | null } };

export type ProductPageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductPageCollectionFilter>;
}>;


export type ProductPageCollectionConnectionQuery = { __typename?: 'Query', ProductPageCollectionConnection: { __typename?: 'ProductPageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProductPageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'ProductPageCollection', id: string, hidden?: boolean | null, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'ProductPageCollectionMetadata', title?: string | null, description?: string | null } | null, images?: Array<{ __typename: 'ProductPageCollectionImages', image: string } | null> | null } | null } | null> | null } };

export type PoliciesAndPricingPageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PoliciesAndPricingPageCollectionQuery = { __typename?: 'Query', PoliciesAndPricingPageCollection: { __typename?: 'PoliciesAndPricingPageCollection', id: string, title: string, heroImage: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'PoliciesAndPricingPageCollectionMetadata', title?: string | null, description?: string | null } | null } };

export type PoliciesAndPricingPageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PoliciesAndPricingPageCollectionFilter>;
}>;


export type PoliciesAndPricingPageCollectionConnectionQuery = { __typename?: 'Query', PoliciesAndPricingPageCollectionConnection: { __typename?: 'PoliciesAndPricingPageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PoliciesAndPricingPageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'PoliciesAndPricingPageCollection', id: string, title: string, heroImage: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'PoliciesAndPricingPageCollectionMetadata', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export type AboutUsPageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutUsPageCollectionQuery = { __typename?: 'Query', AboutUsPageCollection: { __typename?: 'AboutUsPageCollection', id: string, title: string, newOwnershipBody?: any | null, aboutTheFounderBody?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'AboutUsPageCollectionMetadata', title?: string | null, description?: string | null } | null, ownerPhotos?: Array<{ __typename: 'AboutUsPageCollectionOwnerPhotos', image: string } | null> | null, founderPhotos?: Array<{ __typename: 'AboutUsPageCollectionFounderPhotos', image: string } | null> | null } };

export type AboutUsPageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutUsPageCollectionFilter>;
}>;


export type AboutUsPageCollectionConnectionQuery = { __typename?: 'Query', AboutUsPageCollectionConnection: { __typename?: 'AboutUsPageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutUsPageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'AboutUsPageCollection', id: string, title: string, newOwnershipBody?: any | null, aboutTheFounderBody?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'AboutUsPageCollectionMetadata', title?: string | null, description?: string | null } | null, ownerPhotos?: Array<{ __typename: 'AboutUsPageCollectionOwnerPhotos', image: string } | null> | null, founderPhotos?: Array<{ __typename: 'AboutUsPageCollectionFounderPhotos', image: string } | null> | null } | null } | null> | null } };

export type AboutThisWebsitePageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutThisWebsitePageCollectionQuery = { __typename?: 'Query', AboutThisWebsitePageCollection: { __typename?: 'AboutThisWebsitePageCollection', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'AboutThisWebsitePageCollectionMetadata', title?: string | null, description?: string | null } | null } };

export type AboutThisWebsitePageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutThisWebsitePageCollectionFilter>;
}>;


export type AboutThisWebsitePageCollectionConnectionQuery = { __typename?: 'Query', AboutThisWebsitePageCollectionConnection: { __typename?: 'AboutThisWebsitePageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutThisWebsitePageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'AboutThisWebsitePageCollection', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'AboutThisWebsitePageCollectionMetadata', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export type ContactUsPageCollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactUsPageCollectionQuery = { __typename?: 'Query', ContactUsPageCollection: { __typename?: 'ContactUsPageCollection', id: string, contactDetails?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'ContactUsPageCollectionMetadata', title?: string | null, description?: string | null } | null } };

export type ContactUsPageCollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactUsPageCollectionFilter>;
}>;


export type ContactUsPageCollectionConnectionQuery = { __typename?: 'Query', ContactUsPageCollectionConnection: { __typename?: 'ContactUsPageCollectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactUsPageCollectionConnectionEdges', cursor: string, node?: { __typename?: 'ContactUsPageCollection', id: string, contactDetails?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metadata?: { __typename: 'ContactUsPageCollectionMetadata', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export const GlobalCollectionPartsFragmentDoc = gql`
    fragment GlobalCollectionParts on GlobalCollection {
  header {
    __typename
    phoneNumber
    socialLinks {
      __typename
      label
      url
    }
    logo
    navigation {
      __typename
      label
      url
      subNavItem {
        __typename
        label
        url
      }
    }
  }
  footer {
    __typename
    label
  }
}
    `;
export const HomePageCollectionPartsFragmentDoc = gql`
    fragment HomePageCollectionParts on HomePageCollection {
  metadata {
    __typename
    title
    description
  }
  heroImage
  cta
  body
  quotes {
    __typename
    quote
    name
  }
}
    `;
export const FlavorPageCollectionPartsFragmentDoc = gql`
    fragment FlavorPageCollectionParts on FlavorPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  body
  heroImage
  flavorGroups {
    __typename
    label
    flavors
  }
}
    `;
export const ProductPageCollectionPartsFragmentDoc = gql`
    fragment ProductPageCollectionParts on ProductPageCollection {
  metadata {
    __typename
    title
    description
  }
  hidden
  title
  body
  images {
    __typename
    image
  }
}
    `;
export const PoliciesAndPricingPageCollectionPartsFragmentDoc = gql`
    fragment PoliciesAndPricingPageCollectionParts on PoliciesAndPricingPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  heroImage
  body
}
    `;
export const AboutUsPageCollectionPartsFragmentDoc = gql`
    fragment AboutUsPageCollectionParts on AboutUsPageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  newOwnershipBody
  ownerPhotos {
    __typename
    image
  }
  aboutTheFounderBody
  founderPhotos {
    __typename
    image
  }
}
    `;
export const AboutThisWebsitePageCollectionPartsFragmentDoc = gql`
    fragment AboutThisWebsitePageCollectionParts on AboutThisWebsitePageCollection {
  metadata {
    __typename
    title
    description
  }
  title
  body
}
    `;
export const ContactUsPageCollectionPartsFragmentDoc = gql`
    fragment ContactUsPageCollectionParts on ContactUsPageCollection {
  metadata {
    __typename
    title
    description
  }
  contactDetails
}
    `;
export const GlobalCollectionDocument = gql`
    query GlobalCollection($relativePath: String!) {
  GlobalCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalCollectionParts
  }
}
    ${GlobalCollectionPartsFragmentDoc}`;
export const GlobalCollectionConnectionDocument = gql`
    query GlobalCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalCollectionFilter) {
  GlobalCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalCollectionParts
      }
    }
  }
}
    ${GlobalCollectionPartsFragmentDoc}`;
export const HomePageCollectionDocument = gql`
    query HomePageCollection($relativePath: String!) {
  HomePageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageCollectionParts
  }
}
    ${HomePageCollectionPartsFragmentDoc}`;
export const HomePageCollectionConnectionDocument = gql`
    query HomePageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageCollectionFilter) {
  HomePageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageCollectionParts
      }
    }
  }
}
    ${HomePageCollectionPartsFragmentDoc}`;
export const FlavorPageCollectionDocument = gql`
    query FlavorPageCollection($relativePath: String!) {
  FlavorPageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FlavorPageCollectionParts
  }
}
    ${FlavorPageCollectionPartsFragmentDoc}`;
export const FlavorPageCollectionConnectionDocument = gql`
    query FlavorPageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FlavorPageCollectionFilter) {
  FlavorPageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FlavorPageCollectionParts
      }
    }
  }
}
    ${FlavorPageCollectionPartsFragmentDoc}`;
export const ProductPageCollectionDocument = gql`
    query ProductPageCollection($relativePath: String!) {
  ProductPageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProductPageCollectionParts
  }
}
    ${ProductPageCollectionPartsFragmentDoc}`;
export const ProductPageCollectionConnectionDocument = gql`
    query ProductPageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProductPageCollectionFilter) {
  ProductPageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProductPageCollectionParts
      }
    }
  }
}
    ${ProductPageCollectionPartsFragmentDoc}`;
export const PoliciesAndPricingPageCollectionDocument = gql`
    query PoliciesAndPricingPageCollection($relativePath: String!) {
  PoliciesAndPricingPageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PoliciesAndPricingPageCollectionParts
  }
}
    ${PoliciesAndPricingPageCollectionPartsFragmentDoc}`;
export const PoliciesAndPricingPageCollectionConnectionDocument = gql`
    query PoliciesAndPricingPageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PoliciesAndPricingPageCollectionFilter) {
  PoliciesAndPricingPageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PoliciesAndPricingPageCollectionParts
      }
    }
  }
}
    ${PoliciesAndPricingPageCollectionPartsFragmentDoc}`;
export const AboutUsPageCollectionDocument = gql`
    query AboutUsPageCollection($relativePath: String!) {
  AboutUsPageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutUsPageCollectionParts
  }
}
    ${AboutUsPageCollectionPartsFragmentDoc}`;
export const AboutUsPageCollectionConnectionDocument = gql`
    query AboutUsPageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutUsPageCollectionFilter) {
  AboutUsPageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutUsPageCollectionParts
      }
    }
  }
}
    ${AboutUsPageCollectionPartsFragmentDoc}`;
export const AboutThisWebsitePageCollectionDocument = gql`
    query AboutThisWebsitePageCollection($relativePath: String!) {
  AboutThisWebsitePageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutThisWebsitePageCollectionParts
  }
}
    ${AboutThisWebsitePageCollectionPartsFragmentDoc}`;
export const AboutThisWebsitePageCollectionConnectionDocument = gql`
    query AboutThisWebsitePageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutThisWebsitePageCollectionFilter) {
  AboutThisWebsitePageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutThisWebsitePageCollectionParts
      }
    }
  }
}
    ${AboutThisWebsitePageCollectionPartsFragmentDoc}`;
export const ContactUsPageCollectionDocument = gql`
    query ContactUsPageCollection($relativePath: String!) {
  ContactUsPageCollection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactUsPageCollectionParts
  }
}
    ${ContactUsPageCollectionPartsFragmentDoc}`;
export const ContactUsPageCollectionConnectionDocument = gql`
    query ContactUsPageCollectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactUsPageCollectionFilter) {
  ContactUsPageCollectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactUsPageCollectionParts
      }
    }
  }
}
    ${ContactUsPageCollectionPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      GlobalCollection(variables: GlobalCollectionQueryVariables, options?: C): Promise<{data: GlobalCollectionQuery, variables: GlobalCollectionQueryVariables, query: string}> {
        return requester<{data: GlobalCollectionQuery, variables: GlobalCollectionQueryVariables, query: string}, GlobalCollectionQueryVariables>(GlobalCollectionDocument, variables, options);
      },
    GlobalCollectionConnection(variables?: GlobalCollectionConnectionQueryVariables, options?: C): Promise<{data: GlobalCollectionConnectionQuery, variables: GlobalCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalCollectionConnectionQuery, variables: GlobalCollectionConnectionQueryVariables, query: string}, GlobalCollectionConnectionQueryVariables>(GlobalCollectionConnectionDocument, variables, options);
      },
    HomePageCollection(variables: HomePageCollectionQueryVariables, options?: C): Promise<{data: HomePageCollectionQuery, variables: HomePageCollectionQueryVariables, query: string}> {
        return requester<{data: HomePageCollectionQuery, variables: HomePageCollectionQueryVariables, query: string}, HomePageCollectionQueryVariables>(HomePageCollectionDocument, variables, options);
      },
    HomePageCollectionConnection(variables?: HomePageCollectionConnectionQueryVariables, options?: C): Promise<{data: HomePageCollectionConnectionQuery, variables: HomePageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageCollectionConnectionQuery, variables: HomePageCollectionConnectionQueryVariables, query: string}, HomePageCollectionConnectionQueryVariables>(HomePageCollectionConnectionDocument, variables, options);
      },
    FlavorPageCollection(variables: FlavorPageCollectionQueryVariables, options?: C): Promise<{data: FlavorPageCollectionQuery, variables: FlavorPageCollectionQueryVariables, query: string}> {
        return requester<{data: FlavorPageCollectionQuery, variables: FlavorPageCollectionQueryVariables, query: string}, FlavorPageCollectionQueryVariables>(FlavorPageCollectionDocument, variables, options);
      },
    FlavorPageCollectionConnection(variables?: FlavorPageCollectionConnectionQueryVariables, options?: C): Promise<{data: FlavorPageCollectionConnectionQuery, variables: FlavorPageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: FlavorPageCollectionConnectionQuery, variables: FlavorPageCollectionConnectionQueryVariables, query: string}, FlavorPageCollectionConnectionQueryVariables>(FlavorPageCollectionConnectionDocument, variables, options);
      },
    ProductPageCollection(variables: ProductPageCollectionQueryVariables, options?: C): Promise<{data: ProductPageCollectionQuery, variables: ProductPageCollectionQueryVariables, query: string}> {
        return requester<{data: ProductPageCollectionQuery, variables: ProductPageCollectionQueryVariables, query: string}, ProductPageCollectionQueryVariables>(ProductPageCollectionDocument, variables, options);
      },
    ProductPageCollectionConnection(variables?: ProductPageCollectionConnectionQueryVariables, options?: C): Promise<{data: ProductPageCollectionConnectionQuery, variables: ProductPageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: ProductPageCollectionConnectionQuery, variables: ProductPageCollectionConnectionQueryVariables, query: string}, ProductPageCollectionConnectionQueryVariables>(ProductPageCollectionConnectionDocument, variables, options);
      },
    PoliciesAndPricingPageCollection(variables: PoliciesAndPricingPageCollectionQueryVariables, options?: C): Promise<{data: PoliciesAndPricingPageCollectionQuery, variables: PoliciesAndPricingPageCollectionQueryVariables, query: string}> {
        return requester<{data: PoliciesAndPricingPageCollectionQuery, variables: PoliciesAndPricingPageCollectionQueryVariables, query: string}, PoliciesAndPricingPageCollectionQueryVariables>(PoliciesAndPricingPageCollectionDocument, variables, options);
      },
    PoliciesAndPricingPageCollectionConnection(variables?: PoliciesAndPricingPageCollectionConnectionQueryVariables, options?: C): Promise<{data: PoliciesAndPricingPageCollectionConnectionQuery, variables: PoliciesAndPricingPageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: PoliciesAndPricingPageCollectionConnectionQuery, variables: PoliciesAndPricingPageCollectionConnectionQueryVariables, query: string}, PoliciesAndPricingPageCollectionConnectionQueryVariables>(PoliciesAndPricingPageCollectionConnectionDocument, variables, options);
      },
    AboutUsPageCollection(variables: AboutUsPageCollectionQueryVariables, options?: C): Promise<{data: AboutUsPageCollectionQuery, variables: AboutUsPageCollectionQueryVariables, query: string}> {
        return requester<{data: AboutUsPageCollectionQuery, variables: AboutUsPageCollectionQueryVariables, query: string}, AboutUsPageCollectionQueryVariables>(AboutUsPageCollectionDocument, variables, options);
      },
    AboutUsPageCollectionConnection(variables?: AboutUsPageCollectionConnectionQueryVariables, options?: C): Promise<{data: AboutUsPageCollectionConnectionQuery, variables: AboutUsPageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: AboutUsPageCollectionConnectionQuery, variables: AboutUsPageCollectionConnectionQueryVariables, query: string}, AboutUsPageCollectionConnectionQueryVariables>(AboutUsPageCollectionConnectionDocument, variables, options);
      },
    AboutThisWebsitePageCollection(variables: AboutThisWebsitePageCollectionQueryVariables, options?: C): Promise<{data: AboutThisWebsitePageCollectionQuery, variables: AboutThisWebsitePageCollectionQueryVariables, query: string}> {
        return requester<{data: AboutThisWebsitePageCollectionQuery, variables: AboutThisWebsitePageCollectionQueryVariables, query: string}, AboutThisWebsitePageCollectionQueryVariables>(AboutThisWebsitePageCollectionDocument, variables, options);
      },
    AboutThisWebsitePageCollectionConnection(variables?: AboutThisWebsitePageCollectionConnectionQueryVariables, options?: C): Promise<{data: AboutThisWebsitePageCollectionConnectionQuery, variables: AboutThisWebsitePageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: AboutThisWebsitePageCollectionConnectionQuery, variables: AboutThisWebsitePageCollectionConnectionQueryVariables, query: string}, AboutThisWebsitePageCollectionConnectionQueryVariables>(AboutThisWebsitePageCollectionConnectionDocument, variables, options);
      },
    ContactUsPageCollection(variables: ContactUsPageCollectionQueryVariables, options?: C): Promise<{data: ContactUsPageCollectionQuery, variables: ContactUsPageCollectionQueryVariables, query: string}> {
        return requester<{data: ContactUsPageCollectionQuery, variables: ContactUsPageCollectionQueryVariables, query: string}, ContactUsPageCollectionQueryVariables>(ContactUsPageCollectionDocument, variables, options);
      },
    ContactUsPageCollectionConnection(variables?: ContactUsPageCollectionConnectionQueryVariables, options?: C): Promise<{data: ContactUsPageCollectionConnectionQuery, variables: ContactUsPageCollectionConnectionQueryVariables, query: string}> {
        return requester<{data: ContactUsPageCollectionConnectionQuery, variables: ContactUsPageCollectionConnectionQueryVariables, query: string}, ContactUsPageCollectionConnectionQueryVariables>(ContactUsPageCollectionConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "https://content.tinajs.io/1.4/content/ec7dd7a6-6248-4faa-9e12-a8333fd8a7f7/github/feat/tina-rewrite", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  