local_backend: true
backend:
  name: test-repo
media_folder: public/images
public_folder: /images
collections:
  - name: pages
    label: Pages
    folder: public/content
    create: true
    identifier_field: title
    slug: '{{slug}}'
    fields:
      - name: title
        widget: string
        label: Title
        required: true
      - name: content
        widget: markdown
        label: Content
        required: true
